#pragma once

#include "../Core/KeyCodes.h"

#define FUTOGUI(x) ImGuiKeyTranslator::FUKeyToImGuiKey(x)

namespace FalseUnion
{
    class ImGuiKeyTranslator
    {
    public:
        static int FUKeyToImGuiKey(int KeyCode)
        {
            switch (KeyCode)
            {
            case FU_KEY_SPACE:
                return 524;
            case FU_KEY_APOSTROPHE:
                return 596;
            case FU_KEY_COMMA:
                return 597;
            case FU_KEY_MINUS:
                return 598;
            case FU_KEY_PERIOD:
                return 599;
            case FU_KEY_SLASH:
                return 600;
            case FU_KEY_0:
                return 536;
            case FU_KEY_1:
                return 537;
            case FU_KEY_2:
                return 538;
            case FU_KEY_3:
                return 539;
            case FU_KEY_4:
                return 540;
            case FU_KEY_5:
                return 541;
            case FU_KEY_6:
                return 542;
            case FU_KEY_7:
                return 543;
            case FU_KEY_8:
                return 544;
            case FU_KEY_9:
                return 545;
            case FU_KEY_SEMICOLON:
                return 601;
            case FU_KEY_EQUAL:
                return 602;
            case FU_KEY_A:
                return 546;
            case FU_KEY_B:
                return 547;
            case FU_KEY_C:
                return 548;
            case FU_KEY_D:
                return 549;
            case FU_KEY_E:
                return 550;
            case FU_KEY_F:
                return 551;
            case FU_KEY_G:
                return 552;
            case FU_KEY_H:
                return 553;
            case FU_KEY_I:
                return 554;
            case FU_KEY_J:
                return 555;
            case FU_KEY_K:
                return 556;
            case FU_KEY_L:
                return 557;
            case FU_KEY_M:
                return 558;
            case FU_KEY_N:
                return 559;
            case FU_KEY_O:
                return 560;
            case FU_KEY_P:
                return 561;
            case FU_KEY_Q:
                return 562;
            case FU_KEY_R:
                return 563;
            case FU_KEY_S:
                return 564;
            case FU_KEY_T:
                return 565;
            case FU_KEY_U:
                return 566;
            case FU_KEY_V:
                return 567;
            case FU_KEY_W:
                return 568;
            case FU_KEY_X:
                return 569;
            case FU_KEY_Y:
                return 570;
            case FU_KEY_Z:
                return 571;
            case FU_KEY_LEFT_BRACKET:
                return 603;
            case FU_KEY_BACKSLASH:
                return 604;
            case FU_KEY_RIGHT_BRACKET:
                return 605;
            case FU_KEY_GRAVE_ACCENT:
                return 606;
            case FU_KEY_ESCAPE:
                return 526;
            case FU_KEY_ENTER:
                return 525;
            case FU_KEY_TAB:
                return 512;
            case FU_KEY_BACKSPACE:
                return 523;
            case FU_KEY_INSERT:
                return 521;
            case FU_KEY_DELETE:
                return 522;
            case FU_KEY_RIGHT:
                return 514;
            case FU_KEY_LEFT:
                return 513;
            case FU_KEY_DOWN:
                return 516;
            case FU_KEY_UP:
                return 515;
            case FU_KEY_PAGE_UP:
                return 517;
            case FU_KEY_PAGE_DOWN:
                return 518;
            case FU_KEY_HOME:
                return 519;
            case FU_KEY_END:
                return 520;
            case FU_KEY_CAPS_LOCK:
                return 607;
            case FU_KEY_SCROLL_LOCK:
                return 608;
            case FU_KEY_NUM_LOCK:
                return 609;
            case FU_KEY_PRINT_SCREEN:
                return 610;
            case FU_KEY_PAUSE:
                return 611;
            case FU_KEY_F1:
                return 572;
            case FU_KEY_F2:
                return 573;
            case FU_KEY_F3:
                return 574;
            case FU_KEY_F4:
                return 575;
            case FU_KEY_F5:
                return 576;
            case FU_KEY_F6:
                return 577;
            case FU_KEY_F7:
                return 578;
            case FU_KEY_F8:
                return 579;
            case FU_KEY_F9:
                return 580;
            case FU_KEY_F10:
                return 581;
            case FU_KEY_F11:
                return 582;
            case FU_KEY_F12:
                return 583;
            case FU_KEY_F13:
                return 584;
            case FU_KEY_F14:
                return 585;
            case FU_KEY_F15:
                return 586;
            case FU_KEY_F16:
                return 587;
            case FU_KEY_F17:
                return 588;
            case FU_KEY_F18:
                return 589;
            case FU_KEY_F19:
                return 590;
            case FU_KEY_F20:
                return 591;
            case FU_KEY_F21:
                return 592;
            case FU_KEY_F22:
                return 593;
            case FU_KEY_F23:
                return 594;
            case FU_KEY_F24:
                return 595;
            case FU_KEY_F25:
                return 0;
            case FU_KEY_KP_0:
                return 612;
            case FU_KEY_KP_1:
                return 613;
            case FU_KEY_KP_2:
                return 614;
            case FU_KEY_KP_3:
                return 615;
            case FU_KEY_KP_4:
                return 616;
            case FU_KEY_KP_5:
                return 617;
            case FU_KEY_KP_6:
                return 618;
            case FU_KEY_KP_7:
                return 619;
            case FU_KEY_KP_8:
                return 620;
            case FU_KEY_KP_9:
                return 621;
            case FU_KEY_KP_DECIMAL:
                return 622;
            case FU_KEY_KP_DIVIDE:
                return 623;
            case FU_KEY_KP_MULTIPLY:
                return 624;
            case FU_KEY_KP_SUBTRACT:
                return 625;
            case FU_KEY_KP_ADD:
                return 626;
            case FU_KEY_KP_ENTER:
                return 627;
            case FU_KEY_KP_EQUAL:
                return 628;
            case FU_KEY_LEFT_SHIFT:
                return 528;
            case FU_KEY_LEFT_CONTROL:
                return 527;
            case FU_KEY_LEFT_ALT:
                return 529;
            case FU_KEY_LEFT_SUPER:
                return 530;
            case FU_KEY_RIGHT_SHIFT:
                return 532;
            case FU_KEY_RIGHT_CONTROL:
                return 531;
            case FU_KEY_RIGHT_ALT:
                return 533;
            case FU_KEY_RIGHT_SUPER:
                return 534;
            case FU_KEY_MENU:
                return 535;
            default:
                return 0;
            }
        }
    };
}
